### ISSUE TITLE
Tests are failing with `ReferenceError: beforeEach is not defined` error

### ISSUE THREAD

**Issue by andrivet** [maziac/DeZog#135]
**Describe the bug**

When trying to run tests, they are failing with the following error:

```
ReferenceError: beforeEach is not defined
    at Suite.<anonymous> (/Users/kusanagi/Projects/Projects.kusanagi/ZX81/ZX81-Debugger/DeZog/out/tests/customjoystick.tests.js:10:5)
    at Object.create (/Users/kusanagi/Projects/Projects.kusanagi/ZX81/ZX81-Debugger/DeZog/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.suite (/Users/kusanagi/Projects/Projects.kusanagi/ZX81/ZX81-Debugger/DeZog/node_modules/mocha/lib/interfaces/tdd.js:49:27)
    at Object.<anonymous> (/Users/kusanagi/Projects/Projects.kusanagi/ZX81/ZX81-Debugger/DeZog/out/tests/customjoystick.tests.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**To Reproduce**

```
npm i
npm run compile
npm r
```

**Expected behavior**
The tests should run.

**Version etc. (please complete the following information):**
 - DeZog SW Version:  3.5.1
 - OS: [the OS you used]: macOS
 - Remote: zsim or zrcp (ZEsarUX): n/a

**Comment by maziac** [comment]
Strange. it is running in the test explorer (in vscode).

**Comment by andrivet** [comment]
Which vscode extension are you using? I wonder if a config file is missing on GitHub.

**Comment by maziac** [comment]
Now it should work.

**Comment by andrivet** [comment]
Yes it does. Great!
