### ISSUE TITLE
Closing the help once prevents it from being opened again

### ISSUE THREAD

**Issue by remy** [maziac/DeZog#51]
**Describe the bug**

Using the "dezog help" sidebar panel - the first time I click on a help item, a webview opens. 

If I close that webview, and then click on a different help item, nothing happens.

**Expected behavior**

The webview should relaunch to the newly selected help item.

**Version etc. (please complete the following information):**
 - DeZog SW Version: 2.2.0
 - OS: macos
 - Remote: zsim

**Additional context**

In VS Code devtools, clicking the second time or more, shows the following error:

<details>
<summary>ERR Webview is disposed: Error: Webview is disposed</summary>
<pre>
    at r.assertNotDisposed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:62797)
    at reveal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:62645)
    at HelpView.reveal (/Users/remy/.vscode/extensions/maziac.dezog-2.2.0/out/src/views/baseview.js:146:26)
    at HelpProvider.createHelpView (/Users/remy/.vscode/extensions/maziac.dezog-2.2.0/out/src/help/helpprovider.js:195:23)
    at HelpProvider.navigateToChapter (/Users/remy/.vscode/extensions/maziac.dezog-2.2.0/out/src/help/helpprovider.js:203:14)
    at /Users/remy/.vscode/extensions/maziac.dezog-2.2.0/out/src/help/helpprovider.js:32:30
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at d.$onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:53273)
    at p._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:10276)
    at p._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9968)
    at p._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8638)
    at p._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:7440)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:5568
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:29104
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
    at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:20765)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:17659
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at u.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12880)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12228
    at Socket.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:12375)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
</pre>
</details>

**Comment by maziac** [comment]
Fixed in v2.2.1.

**Comment by maziac** [comment]
Thanks for reporting.
